# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_I_9FXdK552EoYq1bglNQPta4Y5wJ1VR
"""

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
df=pd.read_csv('//content/heart.csv')
h=df.head(10)
t=df.tail(10)
print(df.shape)
for i in range(293,283,-1):
  df.drop([i],axis=0,inplace=True)
for i in range(10):
  df.drop([i],axis=0,inplace=True)
dfmt=pd.concat([h,t],axis=0)
dfmt.to_csv("test_file.csv")
data=pd.read_csv('/content/test_file.csv')
print(data)

data=data.sample(frac=1)
data.head(10)
x=data[["chol"]]
y=data["output"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
acc=model.score(X_test,y_test).round(2)
y_pred = model.predict(X_test)
print(acc,'\n',y_pred)
sns.heatmap([y_test,y_pred])

model = LogisticRegression()
model.fit(X_train, y_train)
acc=model.score(X_test,y_test).round(2)
y_pred = model.predict(X_test)
print(acc,'\n',y_pred)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
acc=model.score(X_test,y_test).round(2)
y_pred = model.predict(X_test)
print(acc,'\n',y_pred)

from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
sns.heatmap(cm,annot=True)