# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-21uYnOxsCwiik6ESUgU--Qtwphhkc1S
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
#Load example dataset
tips=sns.load_dataset("tips")
#create a scattter plot
sns.scatterplot(x="total_bill",y="tip",data=tips)
sns.violinplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter Plot of Total Bill vs. Tip")
plt.xlabel("Total Bill($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
tips=pd.read_csv("/content/city_temperature(0).csv")
print(tips)
sns.scatterplot(x="Year",y="AvgTemperature",data=tips)
plt.title("Scatter Plot of Year vs. Temperature")
plt.xlabel("Year")
plt.ylabel("Temperature (c)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#Load example dataset
tips=sns.load_dataset("titanic")
print(tips)
#create a scattter plot
sns.scatterplot(x="survived",y="age",data=tips)
plt.title("Scatter Plot of surved vs. age")
plt.xlabel("Survived")
plt.ylabel("Age")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#Load example dataset
iris=sns.load_dataset("iris")
print(iris)
#compute correlation matrix
correlation_matrix=iris.corr()
#create a heatmap of the correlation matrix
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation heatmap of Iris Dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#Load example dataset
iris=sns.load_dataset("planets")
print(iris)
#compute correlation matrix
correlation_matrix=iris.corr()
#create a heatmap of the correlation matrix
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation heatmap of Planets Dataset")
plt.show()