# -*- coding: utf-8 -*-
"""Web_Scraping_BeautifulSoup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O5ALlegacYwXprg47JH8hmhAcQNqq8Cv

Project 1:
Extracting HTML code of any Website using BeautifulSoup
"""

#Importing Libraries
from bs4 import BeautifulSoup
import requests

#Save the url and  access the web page
a='https://myanimelist.net/'
page=requests.get(a)

#HTML code
h_code=BeautifulSoup(page.text,'html')
print(h_code)

t=h_code.find('title')
print(t)

print(t.text)

"""Project 2:
Extracting HTML code from Webpage and storing Table Data using DataFrame
"""

#Importing Libraries
from bs4 import BeautifulSoup
import requests

#Save the url and  access the web page
a='https://www.forbesindia.com/article/explainers/top-10-richest-people-india/85909/1'
page=requests.get(a)

#HTML code
h_code=BeautifulSoup(page.text,'html')
print(h_code)

#storing tabel information
tabel=h_code.find('table')
print(tabel)

#Storing Heading information
head=h_code.find_all('th')
print(head)

#Saving data into List
h=[]
for i in head:
  h.append(i.text)
print(h)
#List comprehension
h1=[i.text for i in head]
print(h1)

#Creating Data Frame
import pandas as pd
DF=pd.DataFrame(columns=h)
print(DF)

#Loading Row Data
rows=h_code.find_all('tr')
print(rows)

#Storing Row Data in DataFrame
index=0
for i in rows[1:6]:
  erd=i.find_all('td')
  rd=[j.text for j in erd]
  DF.loc[index]=rd
  index=index+1
print(DF)

#Saving to the csv file
DF.to_csv('LovRaj.csv')